#!/usr/bin/env python
"""
Usage:
    zubmit-cli [options] assign <DESCRIPTION> <DUE_DATE>
    zubmit-cli [options] register <STUDENT_LIST>
    zubmit-cli [options] list-students
    zubmit-cli [options] download <ASSIGNMENT_ID>

Options:
    -w <WORD_LIMIT>, --word-limit=<WORD_LIMIT>
        Add a word limit to an assigned task
    -i <NUMBER>, --number-of-images=<NUMBER>
        Allow image uploads [Default: 0]
    -o <OUTPUTFILE>, --output=<OUTPUTFILE>
        Output filename [Default: test.{}]
    -f <FORMAT>, --output-format=<FORMAT>
        Output format [Default: markdown]
    -u <URL>, --url=<URL>
        Url of server [Default: http://127.0.0.1:5000]
"""

from docopt import docopt
from zubmit import cli

if __name__ == '__main__':
    args = docopt(__doc__)
    print(args)

    if args['assign']:
        cli.assign(args, args['--url'])
    elif args['register']:
        cli.register(args, args['--url'])
    elif args['list-students']:
        cli.list_students(args, args['--url'])
    elif args['download']:
        cli.download(args, args['--url'])
